version: '3'
services:
  bitbucket:
    image: 'atlassian/bitbucket-server:latest'
    ports:
      - '7990:7990'
      - '7999:7999'
    volumes:
      - '/var/atlassian/application-data/bitbucket:/var/atlassian/application-data/bitbucket'
